# Generated by Django 2.2.3 on 2019-08-02 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='NewsRoom',
        ),
    ]
