# Generated by Django 2.2.3 on 2019-08-02 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20190802_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsroom',
            name='image',
            field=models.URLField(default='image'),
        ),
        migrations.AlterField(
            model_name='newsroom',
            name='post',
            field=models.TextField(default='posts'),
        ),
    ]
