# Generated by Django 2.2.3 on 2019-08-02 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190802_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsroom',
            name='title',
            field=models.CharField(max_length=300),
        ),
    ]
