# Generated by Django 2.2.3 on 2019-08-02 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20190802_1909'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsroom',
            name='image',
            field=models.URLField(default='https://github.com/macvincent', null=True),
        ),
    ]
