# Generated by Django 2.2.3 on 2019-08-02 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20190802_1918'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
            ],
        ),
        migrations.AlterField(
            model_name='newsroom',
            name='image',
            field=models.URLField(default='#', null=True),
        ),
        migrations.AlterField(
            model_name='newsroom',
            name='post',
            field=models.TextField(default='A Comment..', null=True),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(default='posts', null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.User')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.NewsRoom')),
            ],
        ),
    ]
