# Generated by Django 2.2.3 on 2019-08-03 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20190803_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='name',
        ),
        migrations.AddField(
            model_name='comment',
            name='title',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
