# Generated by Django 2.2.3 on 2019-08-03 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20190803_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsroom',
            name='url',
            field=models.URLField(default='#'),
        ),
    ]
