# Generated by Django 2.2.3 on 2019-08-03 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_newsroom_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsroom',
            name='source',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
