# Generated by Django 2.2.5 on 2019-11-24 08:01

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_newsroom_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsroom',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=blog.models.get_image_path),
        ),
        migrations.AlterField(
            model_name='newsroom',
            name='source',
            field=models.TextField(default='Unknown source', null=True),
        ),
        migrations.AlterField(
            model_name='newsroom',
            name='title',
            field=models.TextField(default='Unknown source', null=True),
        ),
        migrations.AlterField(
            model_name='newsroom',
            name='url',
            field=models.TextField(default='#', null=True),
        ),
    ]
