# Generated by Django 2.2.5 on 2019-11-25 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_auto_20191124_0902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsroom',
            name='image',
            field=models.TextField(default='Image url', null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
